name: Settings

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.9", "3.10", "3.11"]

    name: ${{ matrix.os }} | Python ${{ matrix.python }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Python Installing
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"

      - name: Requirements Installing
        run: pip install -r requirements.txt

      - name: Tests
        run: python -m unittest discover tests/
